return{
	require("config.plug.autopairs"),
	require("config.plug.dashboard"),
	require("config.plug.comment"),
	require("config.plug.cmp"),
	require("config.plug.gitsigns"),
	require("config.plug.lualine"),
	require("config.plug.nvimtree"),
	require("config.plug.stablize"),
	require("config.plug.tabline"),
	require("config.plug.telescope"),
}
