--require("stabilize").setup()
require("nvim-tree").setup()
require("todo-comments").setup()
require("nvim_comment").setup()
require("gitsigns").setup()
require("flutter-tools").setup({}) -- use defaults

require("config.mason")
require("config.winbar")
require("config.lualine")
require("config.cursorline")
require("config.bufferline")
require("config.cmp")
require("config.blankline")
require("config.telescope")
require("config.nvim-treesitter")
require("config.formatter")
